kind: pipeline
name: deploy

steps:
  - name: unit-test
    image: node:12.2.0-alpine
    commands:
      - npm install
      - npm run lint
      - npm run test
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push
          - pull_request

  - name: get-tag-no
    image: ubuntu
    commands:    
      - bash ./scripts/build-tag.sh   

  - name: publish-test-image
    image: plugins/docker
    settings:
      repo: myhk2009/docker-ci    # drone-owner/drone-repo
      username: 
        from_secret: DOCKER_USERNAME   # drone a/c
      auto_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      tag:
        - ${TAG_NO}
    when:
      branch: feature/*
      event: 
        include:
          - push      
          - pull_request

  # - name: deploy-image
  #   image: appleboy/drone-ssh
  #   pull: true  # always pull the latest version of the `drone-ssh` plugin
  #   secrets: [ ssh_username, ssh_password ]
  #   host: http://localhost
  #   port: 22
  #   command_timeout: 180
  #   script:
  #     - /bin/bash ./scripts/deploy.sh  # or whereever you put your `deploy.sh`
  #   when:
  #     event: [push, tag, deployment]

  - name: notify
    image: drillster/drone-email
    from: myhkapple@gmail.com
    host: smtp.gmail.com
    port: 465
    username: myhkapple@gmail.com
    password: abcd_1234
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ build.branch }} - {{ truncate build.commit 8 }})
    body: >
      https://git.io/vgvPz