kind: pipeline
name: deploy

steps:
  - name: unit-test
    image: node:12.2.0-alpine
    commands:
      - npm install
      - npm run lint
      - npm run test
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push
          - pull_request

  - name: get-tag-no
    image: alpine
    commands:
      - sh ./scripts/build-tag.sh
      - echo $$EMAIL_USERNAME
      - echo $$EMAIL_PASSWORD
      - echo $$EMAIL_HOST
      - echo $$EMAIL_PORT


  - name: publish-test-image
    image: plugins/docker
    settings:
      repo: docker.io/myhk2009/docker-ci  #private image: add docker.io
      registry: docker.io
      username: #myhk2009
        from_secret: DOCKER_USERNAME   # docker hub a/c
      password: #abcd_1234
        from_secret: DOCKER_PASSWORD
      tag: [1, 1.0, latest]
        #- ${TAG_NO}
      commands:
        - docker version
    when:
      branch: feature/*
      event: 
        include:
          - push      
          - pull_request

  # - name: deploy-image
  #   image: appleboy/drone-ssh
  #   pull: true  # always pull the latest version of the `drone-ssh` plugin
  #   secrets: [ ssh_username, ssh_password ]
  #   host: http://localhost
  #   port: 22
  #   command_timeout: 180
  #   script:
  #     - /bin/bash ./scripts/deploy.sh  # or whereever you put your `deploy.sh`
  #   when:
  #     event: [push, tag, deployment]

  # - name: notify
  #   image: drillster/drone-email
  #   from: myhkapple@gmail.com
  #   recipients:
  #     - myhkapple@gmail.com
  #   secrets: [ email_username, email_password, email_host, email_port ]      
  #   skip_verify: true
  #   subject: >
  #     [{{ build.status }}]
  #     {{ repo.owner }}/{{ repo.name }}
  #     ({{ build.branch }} - {{ truncate build.commit 8 }})
  #   body: >
  #     https://git.io/vgvPz

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: dev
      username: myhk2009
    when:
        status: [ success, failure ]
    template: >
        {{#success build.status}}
            {{build.author}} trigger {{repo.name}} build {{build.number}} by {{build.event}} to branch {{build.branch}} succeeded.
            <{{build.link}}>
        {{else}}
            {{repo.name}} build {{build.number}} to branch {{build.branch}} failed. Fix me please.
            <{{build.link}}>
        {{/success}}

    branches: [ master, develop, feature/* ]