kind: pipeline
name: deploy

steps:
  - name: unit-test
    image: node:12.2.0-alpine
    commands:
      - npm install
      - npm run lint
      - npm run test
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push

  - name: get-tag-no
    image: alpine
    commands:
      - sh ./scripts/build-tag.sh
      - echo $EMAIL_USERNAME
      - echo ${EMAIL_USERNAME}
      - echo $$EMAIL_USERNAME
      - echo $${EMAIL_USERNAME}
      - echo "$EMAIL_USERNAME"
      - echo "${EMAIL_USERNAME}"
      - echo "$$EMAIL_USERNAME"
      - echo "$${EMAIL_USERNAME}"


  # - name: publish-test-image
  #   image: plugins/docker
  #   settings:
  #     repo: myhk2009/docker-ci
  #     username: 
  #       from_secret: DOCKER_USERNAME   # docker hub a/c
  #     password:
  #       from_secret: DOCKER_PASSWORD
  #     tag:
  #       - ${TAG_NO}
  #   when:
  #     branch: feature/*
  #     event: 
  #       include:
  #         - push      
  #         - pull_request

  # - name: deploy-image
  #   image: appleboy/drone-ssh
  #   pull: true  # always pull the latest version of the `drone-ssh` plugin
  #   secrets: [ ssh_username, ssh_password ]
  #   host: http://localhost
  #   port: 22
  #   command_timeout: 180
  #   script:
  #     - /bin/bash ./scripts/deploy.sh  # or whereever you put your `deploy.sh`
  #   when:
  #     event: [push, tag, deployment]

  # - name: notify
  #   image: drillster/drone-email
  #   from: postmaster@sandbox82a395c2932442a980c051ce66c51038.mailgun.org
  #   recipients:
  #     - myhk2009@gmail.com
  #   host: smtp.mailgun.org
  #   username: postmaster@sandbox82a395c2932442a980c051ce66c51038.mailgun.org
  #   password: 387eeadb70d66d2c496718aaf7adb18d-87cdd773-091417db
  #   subject: >
  #     [{{ build.status }}]
  #     {{ repo.owner }}/{{ repo.name }}
  #     ({{ build.branch }} - {{ truncate build.commit 8 }})
  #   body: >
  #     https://git.io/vgvPz

  - name: slack
    image: plugins/slack
    settings:
      webhook: # https://hooks.slack.com/services/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
        from_secret: SLACK_WEBHOOK
      channel: dev
      username: myhk2009
    when:
        status: [ success, failure ]
    template: >
        {{#success build.status}}
            {{build.author}} trigger {{repo.name}} build {{build.number}} by {{build.event}} to branch {{build.branch}} succeeded.
            <{{build.link}}>
        {{else}}
            {{repo.name}} build {{build.number}} to branch {{build.branch}} failed. Fix me please.
            <{{build.link}}>
        {{/success}}

    branches: [ master, develop, feature/* ]