language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: unit tests
      script: 'npm run lint'
    - stage: test staging
      script: 'npm run test'

notifications:
  email:
    recipients:
    - myhk2009@gmail.com
    on_success: always
    on_failure: always