language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Lint Test
    script: npm run lint
  - stage: Unit Test
    script: npm run test
  - stage: Build
    script: npm run build
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: $HEROKU_CITEST2009
      app: citest2019
      on:
        all_branches: true
      skip_cleanup: true
notifications:
  email:
    recipients:
    - myhk2009@gmail.com
    on_success: always
    on_failure: always
    
