language: node_js
node_js:
  - "10"
    
jobs:
  include:
    - stage: Lint Test
      script: 'npm run lint'
      cache:
        directories:
          - 'node_modules'
          
    - stage: Unit Test
      script: 'npm run test'

    - stage: Build
      script: 'npm run build' 

notifications:
  email:
    recipients:
    - myhk2009@gmail.com
    on_success: always
    on_failure: always