version: "2"

services:
  drone-server:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - 8000:8000
      - 9000
    volumes:
      - /var/lib/drone:/data
    restart: always
    environment:
      - DRONE_DEBUG=true
      - DRONE_HOST=http://drone-server:8000
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=e393fbc14e818c40e903
      - DRONE_GITHUB_CLIENT_SECRET=511fb461d7fb1f72bec6a8d581bae6566a6597dd
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SECRET=secret
      - DRONE_USER_CREATE=username:johnchan2016,admin:true
      - DRONE_SERVER_PROTO=http
    networks:
      - appnet

  drone-agent:
    image: drone/agent:1
    container_name: drone-agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_DEBUG=true
      - DRONE_SERVER=http://drone-server:9000
      - DRONE_SECRET=secret
    networks:
      - appnet

networks:
  appnet:
    external: true